//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stanochki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id_user { get; set; }
        public string name { get; set; }
        public string surn { get; set; }
        public string middlen { get; set; }
        public Nullable<int> office { get; set; }
        public string address { get; set; }
        public string number { get; set; }
    
        public virtual Entry Entry { get; set; }
        public virtual Offices Offices { get; set; }
    }
}
